parameters:

services:
    cs_user.registration.form.type:
        class: CS\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cs_user_registration }
    authentication_handler:
        class:  CS\UserBundle\Handler\LoginSuccessHandler
        arguments:  [@router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }