services:
    cs_user.registration.form.type:
        class: CS\UserBundle\Form\Type\RegistrationFormUtilisateurType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cs_utilisateur_registration_form }
    cs_fournisseur.registration.form.type:
        class: CS\UserBundle\Form\Type\RegistrationFormFournisseurType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cs_fournisseur_registration_form }
    authentication_handler:
        class:  CS\UserBundle\Handler\LoginSuccessHandler
        arguments:  ['@router', '@security.context']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
