parameters:
#    cs_user.example.class: CS\UserBundle\Example

services:
    cs_user.registration.form.type:
        class: CS\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cs_user_registration }