imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
<<<<<<< HEAD
        collect: false
=======
        enabled: false
>>>>>>> a9ec11a3ccfdace1b9ea1f2f561120defc296c6d

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
