imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    taggable:
                        type: annotation
                        prefix: DoctrineExtensions\Taggable\Entity
                        dir: "%kernel.root_dir%/../vendor/fpn/doctrine-extensions-taggable/metadata"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: CS\UserBundle\Entity\Utilisateur
    # Permet de renseigner le nouveau formulaire d'inscription
    registration:
        form:
            type: cs_user_registration

#Sylius Configuration

sylius_resource:
    resources:
        app.user:
            driver: doctrine/orm
            templates: CSUserBundle:User
            classes:
                model: CS\UserBundle\Entity\Utilisateur
                
sylius_product:
    driver: doctrine/orm # Configure the doctrine orm driver used in the documentation.
    classes:
        product:
            model: CS\ProductBundle\Entity\Product
            controller: CS\ProductBundle\Controller\ProductController

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true
            
sylius_order:
    driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
    classes:
        order:
            model: CS\ProductBundle\Entity\Order
        sellable:
            model: CS\ProductBundle\Entity\Product # Your product entity.
         # The order entity.
  #order_item:
            #model: Sylius\Bundle\CoreBundle\Model\OrderItem
            
sylius_cart:
    #driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
    resolver: cs_product.cart_item_resolver # The id of our newly created service.
    classes:
        item:
            form: CS\ProductBundle\Entity\CartItem # The item entity.
            
#sylius_promotions:
#    driver: doctrine/orm # Configure the doctrine orm driver used in the documentation.
    
sylius_money:
    driver: doctrine/orm
    
fpn_tag:
    model:
        tag_class:     CS\CommunityBundle\Entity\Community
        tagging_class: CS\CommunityBundle\Entity\CommunitySubscribing
        
services:
    cs.form.community_entry:
        class: CS\CommunityBundle\Form\Type\CommunityType
        arguments: [ "@fpn_tag.tag_manager" ]
        tags:
            - { name: form.type, alias: community_entry }

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter   : [standard, lowercase, asciifolding]
                            custom_index_analyzer:
                                type: custom
                                tokenizer: standard
                                filter   : [standard, lowercase, asciifolding, custom_filter]
                        filter:
                            custom_filter:
                                type: edgeNGram
                                side: front
                                min_gram: 1
                                max_gram: 20
            types:
                user:
                    mappings:
                        nom: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
                        prenom: { boost: 3 }
                    persistence:
                        driver: orm
                        model: CS\UserBundle\Entity\Utilisateur
                        provider: ~
                        finder: ~
