cs_fournisseur:
    resource: "@CSFournisseurBundle/Resources/config/routing.yml"
    prefix:   /fournisseur

cs_admin:
    resource: "@CSAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

cs_product:
    resource: "@CSProductBundle/Resources/config/routing.yml"
    
cs_community:
    resource: "@CSCommunityBundle/Resources/config/routing.yml"
    prefix:   /

cs_design:
    resource: "@CSDesignBundle/Resources/config/routing.yml"
    prefix:   /

cs_user:
    resource: "@CSUserBundle/Resources/config/routing.yml"
    prefix:   /
    
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
   
sylius_product:
    resource: "@SyliusProductBundle/Resources/config/routing.yml"
    
    
_imagine:
    resource: .
    type: imagine

cs_user_show:
    pattern: /users/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.user:showAction

