security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CLIENT:      ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_FOURNISSEUR: ROLE_USER

    providers:
        fos_userbundle:
             id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ 
#        admin:
#            pattern: ^/admin
#            form_login:
#                login_path: /admin/login
#                check_path: /admin/login_check
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#                always_use_default_target_path: true
#                default_target_path: /admin
#            logout: 
#                path:   /admin/logout
#                target: /admin
#            anonymous:    false
#            remember_me:
#                key: "%secret%"
#                lifetime: 31536000 # 365 days in seconds
#                path: /admin
#                domain: ~ 
#        fournisseur:
#            pattern: ^/fournisseur
#            form_login:
#                check_path: /login_check
#                login_path: /login
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#                always_use_default_target_path: true
#                default_target_path: /fournisseur
#            logout: 
#                path:   /logout
#                target: /fournisseur
#            anonymous:    true
#            remember_me:
#                key: "%secret%"
#                lifetime: 31536000 # 365 days in seconds
#                path: /fournisseur
#                domain: ~ 

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/fournisseur/, role: ROLE_FOURNISSEUR }
        - { path: ^/user/, role: ROLE_USER }
