sylius_product:
    resource: @CSProductBundle/Resources/config/routing/product.yml
    prefix: /products    

sylius_property:
    resource: @SyliusProductBundle/Resources/config/routing/property.yml
    prefix: /properties