sylius_product:
    resource: @CSProductBundle/Resources/config/routing/product.yml
    prefix: /products    

sylius_property:
    resource: @SyliusProductBundle/Resources/config/routing/property.yml
    prefix: /properties
    
search_product:
    pattern: /product/search
    defaults:  { _controller: CSProductBundle:Search:search }