sylius_product:
    resource: "@CSProductBundle/Resources/config/routing/product.yml"
    prefix: /products    

sylius_property:
    resource: "@SyliusProductBundle/Resources/config/routing/property.yml"
    prefix: /properties

    
search_product_by_type:
    pattern: /product/{type}
    methods: [GET]
    defaults:  { _controller: "CSProductBundle:Search:showByType" }
    
search_product:
    pattern: /product/search
    defaults:  { _controller: "CSProductBundle:Search:search" }
    
search_product_by_type:
    pattern: /product/search/{type}
    methods: [GET]
    defaults:  { _controller: "CSProductBundle:Search:searchByType" }
