cs_product:
    resource: "@CSProductBundle/Resources/config/routing/product.yml"
    prefix: /products       
search_product_by_type:
    pattern: /product/{type}
    methods: [GET]
    defaults:  { _controller: "CSProductBundle:Search:showByType" }
    
search_product:
    pattern: /product/search
    defaults:  { _controller: "CSProductBundle:Search:search" }
    
search_product_by_type:
    pattern: /product/search/{type}
    methods: [GET]
    defaults:  { _controller: "CSProductBundle:Search:searchByType" }
    
search_product_not_free:
    pattern: /notfree
    methods: [GET]
    defaults:  { _controller: "CSProductBundle:Search:searchNotFree" }
search_free_product:
    pattern: /free
    methods: [GET]
    defaults:  { _controller: "CSProductBundle:Search:searchFree" }
