parameters:
#    cs_fournisseur.example.class: CS\FournisseurBundle\Example

services:
#    cs_fournisseur.example:
#        class: %cs_fournisseur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
