page_community:
    pattern: /page_community/{communityName}
    defaults: { _controller: "CSCommunityBundle:Community:pageCommunity" }

show_all_communities:
    pattern: /show_all_communities
    defaults:  { _controller: "CSCommunityBundle:Community:showCommunitiesType"}

show_all_communities_of:
    pattern: /show_all_communities_of/{product_id}
    defaults:  { _controller: "CSCommunityBundle:Community:showAllCommunitiesOf"}

cs_community_admin:
    resource: "@CSCommunityBundle/Resources/config/Admin/routing.yml"
    prefix:   /admin
    
cs_community_user:
    resource: "@CSCommunityBundle/Resources/config/User/routing.yml"
    prefix:   /user

cs_community_fournisseur:
    resource: "@CSCommunityBundle/Resources/config/Fournisseur/routing.yml"
    prefix:   /fournisseur
    
search_communities_by_theme:
    pattern: /theme/{theme_id}
    methods: [GET]
    defaults:  { _controller: "CSCommunityBundle:Community:searchCommunitiesByTheme" }    