parameters:
#    cs_admin.example.class: CS\AdminBundle\Example

services:
#    cs_admin.example:
#        class: %cs_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
