sylius_product_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            sortable: true
            sorting:
              name: desc

sylius_product_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            redirect: sylius_product_show


sylius_product_create_music:
    pattern: /new/music
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createMusicAction
        _sylius:
            redirect: sylius_product_show

sylius_product_create_video:
    pattern: /new/video
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createVideoAction
        _sylius:
            redirect: sylius_product_show
            
sylius_product_create_book:
    pattern: /new/book
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createBookAction
        _sylius:
            redirect: sylius_product_show
            
sylius_product_create_game:
    pattern: /new/game
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createGameAction
        _sylius:
            redirect: sylius_product_show
            
sylius_product_create_ticket:
    pattern: /new/ticket
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createTicketAction
        _sylius:
            redirect: sylius_product_show
            
sylius_product_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            redirect: sylius_product_show

sylius_product_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.product:deleteAction
        _sylius:
            redirect: sylius_product_index

sylius_product_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:showProductAction
