cs_product_index:
    pattern: /
    defaults:  { _controller: "CSProductBundle:Product:index" }

cs_product_create_music:
    pattern: /new/music
    defaults: { _controller: "CSProductBundle:Product:createMusic" }

cs_product_create_video:
    pattern: /new/video
    defaults: { _controller: "CSProductBundle:Product:createVideo" }
            
cs_product_create_book:
    pattern: /new/book 
    defaults: { _controller: "CSProductBundle:Product:createBook" }
            
cs_product_create_game:
    pattern: /new/game
    defaults: { _controller: "CSProductBundle:Product:createGame" }
            
cs_product_create_ticket:
    pattern: /new/ticket
    defaults: { _controller: "CSProductBundle:Product:createTicket" }
            

cs_product_show:
    pattern: /{id}
    defaults:    { _controller: "CSProductBundle:Product:showProduct" }
