cs_product_index:
    pattern: fournisseur/
    defaults:  { _controller: "CSProductBundle:Product:index" }

cs_product_create_music:
    pattern: fournisseur/new/music
    defaults: { _controller: "CSProductBundle:Product:createMusic" }

cs_product_create_video:
    pattern: fournisseur/new/video
    defaults: { _controller: "CSProductBundle:Product:createVideo" }
            
cs_product_create_book:
    pattern: fournisseur/new/book 
    defaults: { _controller: "CSProductBundle:Product:createBook" }
            
cs_product_create_game:
    pattern: fournisseur/new/game
    defaults: { _controller: "CSProductBundle:Product:createGame" }
            
cs_product_create_ticket:
    pattern: fournisseur/new/ticket
    defaults: { _controller: "CSProductBundle:Product:createTicket" }
  
cs_product_download:
    pattern: /download/{product_id}
    defaults: { _controller: "CSProductBundle:Product:download" }          

cs_product_show:
    pattern: /{id}
    defaults:    { _controller: "CSProductBundle:Product:showProduct" }
